
SELECT  TOP 11 Curso, SUM(QTD_ING) AS Inscritos, SUM(QTD_CONC) AS Formandos, SUM(QTD_VAGAS) AS VAGAS_TOT
FROM (
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGASS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGASS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE QT_ING < 99999999
	GROUP BY NO_CINE_ROTULO
) AS A
GROUP BY CURSO
ORDER BY SUM(QTD_ING) DESC
---ORDER BY SUM(QTD_CONC) DESC
---ORDER BY SUM(QTD_VAGAS) DESC


 