/* Ver realação de mulheres no cursos de engenharia ao passar dos anos
objetivo = Ver se a quantidade de mulheres por curso de engenharia vem aumentando, pois sempre disseram que os homens
são mais numerosos nesse tipo de curso
*/

---Fazer um gráfico
SELECT ANO, MULHER, HOMEM, TOTAL, MULHER*100.0/TOTAL AS PC_M
FROM (
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	union
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
	UNION
	SELECT  NU_ANO_CENSO AS ANO, SUM(COALESCE([QT_ING_FEM], 0)) AS Mulher, SUM(COALESCE([QT_ING_MASC], 0)) AS Homem,  
	SUM(COALESCE([QT_ING], 0)) AS Total
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE UPPER(NO_CINE_ROTULO) LIKE 'Engenharia%'
	GROUP BY NU_ANO_CENSO
) A


--- QUANDO COLOQUEI OS DADOS NO SQL VI QUE EM MÉDIA AS MULHERES SEMPRE REPRESENTAM POR VOLTA DE 25%,
---E NOS ANOS DE 2015 A 2019 CAIU O NUMERO DE INGRESSANTE EM UNIVERSIDADE 