
SELECT ANO, CURSO, QTD_INGR, QTD_VAGAS
FROM (
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR, 
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE NO_CINE_ROTULO LIKE 'Administração' 
	OR NO_CINE_ROTULO LIKE 'Pedagogia'
	OR NO_CINE_ROTULO LIKE 'Educação física	'
	OR NO_CINE_ROTULO LIKE 'Direito'
	OR NO_CINE_ROTULO LIKE 'Engenharia civil'
	OR NO_CINE_ROTULO LIKE 'Sistemas de informação'
	OR NO_CINE_ROTULO LIKE 'Contabilidade'
	OR NO_CINE_ROTULO LIKE 'Gestão de pessoas'
	OR NO_CINE_ROTULO LIKE 'Enfermagem'
	OR NO_CINE_ROTULO LIKE 'Psicologia'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO

)A
ORDER BY ANO ASC

SELECT ANO, CURSO, QTD_INGR, QTD_VAGAS
FROM (
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR, 
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE NO_CINE_ROTULO LIKE 'Administração' 
	OR NO_CINE_ROTULO LIKE 'Pedagogia'
	OR NO_CINE_ROTULO LIKE 'Educação física	'
	OR NO_CINE_ROTULO LIKE 'Direito'
	OR NO_CINE_ROTULO LIKE 'Engenharia civil'
	OR NO_CINE_ROTULO LIKE 'Sistemas de informação'
	OR NO_CINE_ROTULO LIKE 'Contabilidade'
	OR NO_CINE_ROTULO LIKE 'Gestão de pessoas'
	OR NO_CINE_ROTULO LIKE 'Enfermagem'
	OR NO_CINE_ROTULO LIKE 'Psicologia'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT 
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT
	SUM(COALESCE([QT_ING],0)) AS QTD_INGR,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	OR NO_CINE_ROTULO LIKE 'Administração'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO

)A
ORDER BY ANO ASC
			