
SELECT ANO, CURSO, QTD_CONC, QTD_VAGAS
FROM (
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, 
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO
	UNION
	SELECT SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS, 
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
	NO_CINE_ROTULO AS Curso,
	NU_ANO_CENSO AS Ano
	FROM DBO.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE NO_CINE_ROTULO LIKE 'Educação física'
	GROUP BY NU_ANO_CENSO, NO_CINE_ROTULO

)A
ORDER BY ANO ASC
		