SELECT  
	ANO,CURSO,QTD_VAGAS, QTD_ING, QTD_CONC
FROM (
	SELECT  
		NO_CINE_ROTULO AS Curso,
		SUM(COALESCE([QT_ING],0)) AS QTD_ING,
		NU_ANO_CENSO as ANO,
		SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,
		SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM 
		dbo.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE 
		QT_ING < 99999999 and NO_CINE_ROTULO 
		like 'Engenharia portuária'
	GROUP BY 
		NO_CINE_ROTULO,
		NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE NO_CINE_ROTULO like 'Engenharia portuária' --Não foi divulgado a quantidade de ingressantes, foi o ultimo ano que existiu--
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGASS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGASS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Engenharia portuária'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
) AS A
ORDER BY ANO

SELECT  ANO,CURSO,QTD_VAGAS, QTD_ING, QTD_CONC
FROM (
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2010
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC,SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014
	WHERE NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017
	WHERE NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGASS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGASS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
	UNION
	SELECT  NO_CINE_ROTULO AS Curso, SUM(COALESCE([QT_ING],0)) AS QTD_ING, NU_ANO_CENSO as ANO,
	SUM(COALESCE([QT_CONC],0)) AS QTD_CONC, SUM(COALESCE([QT_VG_TOTAL],0)) AS QTD_VAGAS
	FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022
	WHERE QT_ING < 99999999 and NO_CINE_ROTULO like 'Rochas%'
	GROUP BY NO_CINE_ROTULO, NU_ANO_CENSO
) AS A
ORDER BY ANO


 
 