SELECT *
FROM (
		SELECT dbc.NU_ANO_CENSO,
		NO_MANTENEDORA AS Razão_social,
		dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,
		SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF,
		dbc.CO_IES AS COD_UNIV,
		SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2010 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2010 as dbi 
		ON dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO,
		dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2011 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2012 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2013 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2014 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2015 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2016 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2017 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2018 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2019 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2020 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2021 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2022 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'UNIVERSIDADE CATÓLICA DE SANTOS'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 227

) A

SELECT *
FROM (
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2010 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2010 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2011 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2012 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2013 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2014 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2015 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2016 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2017 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2018 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_ING],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2019 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2020 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2021 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2022 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA CACHOEIRO DE ITAPEMIRIM'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3782

) A

SELECT *
FROM (
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2010 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2010 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2011 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2011 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2012 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2012 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2013 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2013 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		union
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2014 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2014 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2015 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2015 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2016 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2016 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2017 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2017 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2018 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2018 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2019 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2019 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2020 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2020 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2021 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2021 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO'
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		UNION
		SELECT dbc.NU_ANO_CENSO, NO_MANTENEDORA AS Razão_social, dbi.NO_IES as Nome_univ,
		dbi.SG_IES as codigo_fac,SUM(COALESCE([QT_MAT],0)) AS QUANT_TOTA_ALUN, 
		SUM(COALESCE([QT_TEC_TOTAL],0)) AS QUANT_TEC_ADM_FUNC,
		SUM(COALESCE([QT_DOC_TOTAL],0)) AS QUANT_PROF, dbc.CO_IES AS COD_UNIV,SUM(COALESCE([QT_CURSO],0)) AS QUANT_CURSOS
		FROM dbo.MICRODADOS_CADASTRO_CURSOS_2022 as dbc
		INNER JOIN dbo.MICRODADOS_CADASTRO_IES_2022 as dbi on dbc.CO_IES = dbi.CO_IES
		WHERE dbi.NO_IES LIKE 'FACULDADE DE TECNOLOGIA SÃO FRANCISCO' 
		GROUP BY dbc.NU_ANO_CENSO, dbi.NO_IES, dbi.SG_IES, dbc.CO_IES, NO_MANTENEDORA
		HAVING dbc.CO_IES = 3311
		
) A

